name: "pre-release"

on:
    push:
      branches:
        - "master"

jobs:
    pre-release:
      name: "Pre Release"
      
      runs-on: windows-latest
      strategy:
       matrix:
        architecture: [x64, x86]

      steps:
         - uses: actions/checkout@v1
         - name: Set up Python 2.7
           uses: actions/setup-python@v1
           with:
             python-version: 2.7
             architecture: ${{ matrix.architecture }}  
         - name: Install dependencies
           run: |
            python -m pip install --upgrade pip
            pip install pyinstaller
         - name: build with pyinstaller
           run: |
              pyinstaller decode-status.py ds-build-win.spec              
         - name: Upload Release Asset
           id: upload-release-asset 
           uses: actions/upload-release-asset@v1.0.1
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
              asset_path: ./decode-status-${{ matrix.architecture }}.exe
              asset_name: decode-status-${{ matrix.architecture }}.exe
              asset_content_type: application/vnd.microsoft.portable-executable  
