name: "pre-release"

on:
    push:
      branches:
        - "master"

jobs:
    pre-release:
      name: "Pre Release"
      
      runs-on: windows-latest
      strategy:
       matrix:
        architecture: [x64, x86]

      steps:
         - uses: actions/checkout@v1
         - name: Set up Python 2.7
           uses: actions/setup-python@v1
           with:
             python-version: 2.7
             architecture: ${{ matrix.architecture }}  
         - name: Install dependencies
           run: |
            python -m pip install --upgrade pip
            pip install pyinstaller
         - name: build with pyinstaller
           run: |
              pyinstaller decode-status.py ds-build-win.spec
              
         - uses: "marvinpinto/action-automatic-releases@latest"
           with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: "latest"
             prerelease: true
             title: "Development Build"
             files: |
                *.exe           
